version: '3.1'

services:
  userapi:
    image: userapiservice
    build:
      context: .
      dockerfile: UserAPI/Dockerfile
    environment:
      - ConnectionStrings__UserDB="server=Data Source=localhost,5434;Initial Catalog=MovieDB;Persist Security Info=True;User ID=SA;Password=Pass@word"
    ports:
      - "8085:80"
  sql-server:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"